---
- name: Get tree
  community.general.pacman:
    name:
      - "tree"
    state: "present"
  become: true

- name: Get ripgrep
  community.general.pacman:
    name:
      - "ripgrep"
    state: "present"
  become: true

- name: Get zip reader
  community.general.pacman:
    name:
      - "unzip"
    state: "present"
  become: true

- name: Get fd, a better find command
  community.general.pacman:
    name:
      - "fd"
    state: "present"
  become: true

- name: Get treesitter cli
  community.general.pacman:
    name:
      - "tree-sitter-cli"
    state: "present"
  become: true
