---
- name: Generate the locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: "present"
  loop: "{{ [system_lang, system_lc_time, system_lc_numeric] | unique }}"

- name: Set the locales
  ansible.builtin.template:
    src: "locale.conf.j2"
    dest: "/etc/locale.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  register: locales

- name: Check if locales changed
  ansible.builtin.set_fact:
    restart_tasks: "{{ relog_tasks + ['Change locales'] }}"
  when: locales.changed
