---
- name: Set keyboard layout and font for tty
  ansible.builtin.template:
    src: "vconsole.conf.j2"
    dest: "/etc/vconsole.conf"
    mode: "0644"
  become: true
  notify:
    - Apply layout changes
    - Process all preset files in /etc/mkinitcpio.d/
