---
- name: Install necessary packages for pipewire to handle audio
  community.general.pacman:
    name:
      - "pipewire"
      - "wireplumber"
      - "pipewire-audio"
      - "pipewire-alsa"
      - "pipewire-pulse"
      - "pipewire-jack"
    state: "present"
  become: true
  register: install

- name: Require relog if an audio package was installed
  ansible.builtin.set_fact:
    relog_tasks: "{{ relog_tasks + ['Configure audio'] }}"
  when: install.changed
