---
- name: Set keyboard layout for tty
  ansible.builtin.command:
    cmd: "localectl --no-convert set-keymap {{ tty_kb_layout }}"
  become: true

- name: Apply layout changes
  ansible.builtin.command:
    cmd: "/usr/lib/systemd/systemd-vconsole-setup"
  become: true
