---
- name: Install kanshi to handle multiple monitor setups
  community.general.pacman:
    name:
      - "kanshi"
    state: "present"
  become: true

- name: Enable and start the kanshi service
  ansible.builtin.systemd_service:
    scope: "user"
    name: "kanshi"
    state: "started"
    enabled: true
  become: true
  become_user: "{{ username }}"
