---
- name: Get Sway as tiling manager
  community.general.pacman:
    name:
      - "sway"
      - "swayidle"
      - "swaylock"
      - "swaybg"
    state: "present"
  become: true

- name: Get waybar for customizable title bar
  community.general.pacman:
    name:
      - "waybar"
    state: "present"
  become: true

- name: Get XWayland compatibility layer
  community.general.pacman:
    name:
      - "xorg-xwayland"
    state: "present"
  register: xwayland_install
  become: true

- name: Require rebooting sway when xwayland is installed
  ansible.builtin.set_fact:
    restart_sway_tasks: "{{ restart_sway_tasks + ['Configure XWayland'] }}"
  when: xwayland_install.changed
