---
- name: Get Sway as tiling manager
  community.general.pacman:
    name:
      - "sway"
      - "swayidle"
      - "swaylock"
      - "swaybg"
      - "waybar"
      - "foot"
    state: "present"
  become: true
