- name: Bootsrap Arch Linux
  hosts: system
  become: true
  roles:
    - role: system_base
      tags: system_base
    - role: security
      tags: security
    - role: network
      tags: network
    - role: audio
      tags: audio
    - role: maintenance
      tags: maintenance
    - role: display
      tags: display
    - role: chezmoi
      tags: chezmoi
    - role: terminal
      tags: terminal

  vars:
    # List of things that will only apply once restarted.
    restart_tasks: []

    # List of things that will only apply once relogged.
    relog_tasks: []
  tasks:
    - name: Required relog
      ansible.builtin.debug:
        msg: "{{ ['The system will require a relog to apply the following changes:'] + relog_tasks | map('regex_replace', '^', '  - ') | list }}"
      when: relog_tasks | length > 0
      tags: always

    - name: Required restart
      ansible.builtin.debug:
        msg: "{{ ['The system will require a restart to apply the following changes:'] + restart_tasks | map('regex_replace', '^', '  - ') | list }}"
      when: restart_tasks | length > 0
      tags: always
