---
- name: Install keepassxc for password management
  community.general.pacman:
    name:
      - keepassxc
    state: "present"
  become: true

- name: Get qt5-wayland for keepassxc
  community.general.pacman:
    name:
      - qt5-wayland
    state: "present"
  become: true
